name: Build

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    build-for-macos:
        runs-on: macos-11
        steps:
            - uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.17

            - name: Build
              run: ./scripts/darwin/release.sh

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  name: Release ${{ github.ref_name }}
                  files: ./release/darwin/Firecrypt.zip
